### PR TITLE
Revamp Results Log UI

### PR DESCRIPTION
**Pull request by kayla-glick**
image

image

### CODE REVIEW

**Comment by rosenrusinov** [comment]
Damage events and Major Cooldowns could also be linked to the spell id
image
image

**Comment by rosenrusinov** [comment]
Also do you think it would be nicer to make all Number values bold? (Like damage/threat/stacks/etc.)

**Comment by kayla-glick** [comment]
Nice catch thanks @rosenrusinov!

**Comment by kayla-glick** [comment]
@rosenrusinov I did you one better and added colors for resources and damage
image
image

**Comment by kayla-glick** [comment]
I also noticed in that last screenshot that aura stacks needed to be updated to use an Action ID link

**Comment by rosenrusinov** [comment]
This is such a huge improvement from how this screen was. Amazing 🤩

**Pull request merged**
