### PR TITLE
Rogue Tank Changes

### PR DESCRIPTION
**Pull request by sanguinerarogue**
Per zirene conversations going live today

### CODE REVIEW

**Comment by sanguinerarogue** [comment]
image

**Comment by sanguinerarogue** [comment]
image

more comments for implementation

**Comment by emsimpson92** [comment]
Working on Zirene's comments. I'll PR into your branch with my changes

**Comment by sanguinerarogue** [comment]
@kayla-glick all change are implemented here and are now live in game.  Tested in the rogue channel for the values.  Thanks for review!

**Comment by emsimpson92** [comment]
Screenshot_20241122-125359
Updates to UA logic. I can address this later tonight

**Comment by emsimpson92** [comment]
Screenshot_20241122-153439
Updates

**Pull request merged**
