### PR TITLE
Update Ancestral Knowledge talent to increase Mana instead of Intellect

### PR DESCRIPTION
**Pull request by vintage143**
The Ancestral Knowledge talent in Enhancement tree should increase Mana by 5%, not Intellect.

Stats without talent:
Screenshot from 2024-02-08 21-31-52

Before fix:
image

After fix:
image

### CODE REVIEW

**Comment by Foknetics** [comment]
Need to fix the % as well down from 2% per point to 1%

**Review by kayla-glick — APPROVED** [review]

**Comment by kayla-glick** [comment]
Oh dang looks like you just need to update the tests

**Comment by Foknetics** [comment]
the % is still wrong as well, it needs to be 1% per talent point not 2% per talent point

**Review by kayla-glick — CHANGES_REQUESTED** [review]
Updated multiplier + tests then :shipit:

**Comment by vintage143** [comment]
Ah yep my bad. I was doing this well past my regular work hours  😅

**Review by Foknetics — APPROVED** [review]

**Review by kayla-glick — APPROVED** [review]

**Comment by kayla-glick** [comment]
Hey @vintage143 looks like tests are failing again :( would you mind re-running the updater?

**Comment by vintage143** [comment]
@kayla-glick just got around to this. Was too busy playing sod for the last few days :)

**Pull request merged**
